<?php  
	session_start();

	include('config/db_connect.php');


	$car_name = $regNo = $seats = $rate = '';
	$carID = '';
	$error = ['Invalid'=>'', 'booked'=>'','car_name'=>'', 'regNo'=>'', 'seats'=>'', 'rate'=>''];

refresh:
	if(isset($_SESSION['logged_in'])){

		$userName = $_SESSION['username'];
		$indicator = 0;

		if(isset($_POST['add_car'])){
			$indicator = 1;
		}



		if(isset($_POST['carDetail'])){

			if(empty($_POST['car_name'])){
				$error['car_name'] = 'Car name is required <br>';
			} else{
				$car_name = $_POST['car_name'];
			}

			if(empty($_POST['regNo'])){
				$error['regNo'] = 'Registration Number is required <br>';
			} else{
				$regNo = $_POST['regNo'];
			}

			if(empty($_POST['seats'])){
				$error['seats'] = 'Number of seats is required <br>';
			} else{
				$seats = $_POST['seats'];
			}

			if(empty($_POST['rate'])){
				$error['rate'] = 'Rate/day is required <br>';
			} else{
				$rate = $_POST['rate'];
			}


			if(array_filter($error)){

			} else{
				$car_name = mysqli_real_escape_string($conn,$_POST['car_name']);
				$regNo = mysqli_real_escape_string($conn,$_POST['regNo']);
				$seats = mysqli_real_escape_string($conn,$_POST['seats']);
				$rate = mysqli_real_escape_string($conn,$_POST['rate']);

				$sql = "SELECT Owner_ID FROM Owner WHERE username = '$userName'";
				$result = mysqli_query($conn,$sql);
				$getId = mysqli_fetch_assoc($result);
				mysqli_free_result($result);

				$id = $getId['Owner_ID'];

				$sql = "INSERT INTO Car (RegNo,Car_name,no_of_seats,Rate_per_day,Owner_ID,Availability)
						VALUES ('$regNo','$car_name',$seats,$rate,'$id','Available')";
				if(mysqli_query($conn,$sql)){

				} else{
					echo "Error in inserting the record in Car table!!! <br>".mysqli_error($conn);
				}
			}
		}

		

		$sql = "SELECT * FROM Owner WHERE username = '$userName'";
		$result = mysqli_query($conn,$sql);
		$getDetail = mysqli_fetch_assoc($result);


		$sql = "SELECT Count(*) AS total FROM Car c
				INNER JOIN Owner o ON c.Owner_ID = o.Owner_ID AND username = '$userName'";
		$result = mysqli_query($conn,$sql);
		$data = mysqli_fetch_assoc($result);
		mysqli_free_result($result);


		$sql = "SELECT * FROM Car c
				INNER JOIN Owner o ON c.Owner_ID = o.Owner_ID AND username = '$userName' AND Availability <>'UnAvailable'";
		$result = mysqli_query($conn,$sql);
		$Owner_cars = mysqli_fetch_all($result,MYSQLI_ASSOC); 
		mysqli_free_result($result);

		$i = 0;
		foreach ($Owner_cars as $rev_by_car) { // revenue generated by each car
			$temp = $rev_by_car['Car_ID'];

			$sql = "SELECT SUM(Total_amt) AS ttl_rev FROM Car c 
					INNER JOIN Booking b ON c.Car_ID = b.Car_ID 
					INNER JOIN Bill bl ON b.Bill_no = bl.Bill_no AND c.Car_ID = $temp";	

			if(mysqli_query($conn,$sql)){
				$result = mysqli_query($conn,$sql);
				$rev = mysqli_fetch_assoc($result);
				mysqli_free_result($result);

				$temp2[$i]['revenue'] = $rev['ttl_rev']; 
				$i++;
			} else {
				echo mysqli_error($conn);
			}
		}

		for($j=0;($j<$i);$j++){ // adding a new element(revenue) onto the end in each of the index(array) in $Owner_cars
			$Owner_cars[$j]['revenue'] = $temp2[$j]['revenue']; // appending multidimensional associative array
		}


		
		if(isset($_POST['rm_car'])){

			$carID = $_POST['carID'];
			$flag = 0;
			foreach ($Owner_cars as $confirm) {
				if($confirm['Car_ID'] == $carID){
					$flag = 1;
					if($confirm['Availability'] == 'Available'){

						$sql = "UPDATE Car SET Availability = 'Unavailable' WHERE Car_ID = $carID";
						if(mysqli_query($conn,$sql)){
							//echo $_POST['rm_car'];
							unset($_POST['rm_car']);
							//echo $_POST['rm_car'];
							goto refresh;
						} else {
							echo "Error in updating the record in Car table!!! <br>".mysqli_error($conn);
						}

					} else {
						$error['booked'] = 'Car is currently Booked! Cant be removed.';
					}
				}
			}

			if($flag == 0){
				$error['Invalid'] = 'Invalid Car ID';
			}

		}

	} else{
		header('Location: owner_login.php');
	}
?>

<!DOCTYPE html>
<html>

	<?php include('templates/header.php'); ?>

	<div class="jumbotron jumbotron-fluid bg-dark">
		<div class="container">
			<div class="row">


				<div class="col-sm-4 m-auto">
					<ul class="text-white">
						<li>ID: <span class="badge badge-primary badge-pill"><?php echo htmlspecialchars($getDetail['Owner_ID']) ?></span></li>

						<li>NAME: <b><?php echo htmlspecialchars($getDetail['Own_name']) ?></b></li>
						<li>EMAIL: <b><?php echo htmlspecialchars($getDetail['Own_email']) ?></b></li>
						<li>ADDRESS: <b><?php echo htmlspecialchars($getDetail['Own_addr']) ?></b></li>
						<li>CONTACT NO: <b><?php echo htmlspecialchars($getDetail['Own_phone']) ?></b></li>

						<li>Number of Cars: <span class="badge badge-primary badge-pill"><?php echo htmlspecialchars($data['total']) ?></span></li>
					</ul>
				</div>

				
				<div class="col-sm-8">

					<?php if($indicator == 0){ ?>
						<div class="table-responsive">
							<table class="table table-sm table-dark">
								<thead>
									<tr>
										<th>Car ID</th>
										<th>RegNo</th>
										<th>Car Name</th>
										<th>no. of seats</th>
										<th>Rate/day</th>
										<th>Currently</th>
										<th>Revenue Generated</th>
									</tr>
								</thead>
	
								<?php foreach ($Owner_cars as $show) { ?>
									<tr>
										<td><?php echo htmlspecialchars($show['Car_ID']) ?></td>
										<td><?php echo htmlspecialchars($show['RegNo']) ?></td>
										<td><?php echo htmlspecialchars($show['Car_name']) ?></td>
										<td><?php echo htmlspecialchars($show['no_of_seats']) ?></td>
										<td><?php echo htmlspecialchars($show['Rate_per_day']) ?></td>
										<td>
											<?php 
												if($show['Availability'] == 'Available'){
													$show['Availability'] = 'Unbooked';
												}
												echo htmlspecialchars($show['Availability']);
											?>	
										</td>
										<td><?php 
												if($show['revenue'] == NULL){
													$show['revenue'] = 0;
												}
												echo htmlspecialchars($show['revenue']);
											?>
										</td>
									</tr>
							<?php } ?>
	
							<tbody>
								
							</tbody>
						</table>
					</div>

					<form action="panel.php" method="POST" class="float-md-right mb-4">
						<input type="submit" name="rm_car" value="REMOVE CAR" class="btn btn-danger btn-outline-danger text-white">

						<input type="text" name="carID" class="bg-dark text-white" placeholder="Enter Car ID" value="<?php echo htmlspecialchars($carID); ?>">

						<div style="color: tomato;"><?php echo htmlspecialchars($error['Invalid']) ?></div>
						<div style="color: tomato;"><?php echo htmlspecialchars($error['booked']) ?></div>
					</form>

					<form action="panel.php" method="POST">
						<input type="submit" name="add_car" value="NEW CAR" class="btn btn-primary btn-outline-primary text-white">
					</form>



					<?php } else if($indicator == 1){ ?>
						<div class="card bg-secondary w-50 m-auto">
						
							<!-- <div class="card-header"></div>-->

							<div class="card-body">

								<form action="panel.php" method="POST">
								
									<div class="form-group">
										<label class="text-white">CAR NAME</label>
										<input type="text" name="car_name" value="<?php echo htmlspecialchars($car_name); 
											?>" class="form-control" style="height:30px">

											<div style="color: tomato;"><?php echo $error['car_name'] ?></div>
									</div>

									<div class="form-group">
										<label class="text-white">REGISTRATION NUMBER</label>
										<input type="text" name="regNo" value="<?php echo htmlspecialchars($regNo); ?>" 	class="form-control" style="height:30px">

										<div style="color: tomato;"><?php echo $error['regNo'] ?></div>
									</div>

									<div class="form-group">
										<label class="text-white">NUMBER OF SEATS</label>
										<input type="number" name="seats" value="<?php echo htmlspecialchars($seats); ?>" class	="form-control" style="height:30px">

										<div style="color: tomato;"><?php echo $error['seats'] ?></div>
									</div>

									<div class="form-group">
										<label class="text-white">RATE/DAY</label>
										<input type="number" name="rate" value="<?php echo htmlspecialchars($rate); ?>" class="form-control" style="height:30px">

										<div style="color: tomato;"><?php echo $error['rate'] ?></div>
									</div>


									<input type="submit" name="carDetail" value="CONFIRM" class="btn btn-warning btn-outline-warning text-white w-100 mt-3">

								</form>
							</div>

							<!--<div class="card-footer"></div>-->

						</div>	
					<?php } ?>
				</div>


			</div>
		</div>
	</div>

	<?php include('templates/footer.php'); ?>
	
</html>